script:
- echo "skipping tests"

deploy:
  provider: npm
  email: developers@messente.com
  api_key:
    secure: EWqfTzGJBCqSOCfRF1t/JUF5QVW24gYPWqpNS0uAQTlUsN3Zfva/h81k1V4plTHhn0u86kI6VfOzhpE7Z6+U/FJ3w3DFcN0B2wX4rjedMmieQF+/odIUWTNo6sOo+OlsRYgxK3AjU7pm8oMIIv2mpx2XTL44noetwpe0tjXbrwIV+6IzdLXCd3hKWxuatKITRPtQuL6iSbjrHTPCPA+v4F+E2DMTkyq0g8oObOoK2YjMc5P1yQPCa8iH65LNTZlAhmHGf9Y8qSUMKxYT84+vthBMPUHx6q+GNv9NfzfjPJBlrLfIfHtTStWn4tI0cDR19Hj08uLkOAwHTzoor0Nkhdo7NBjFTNu6yWgGS4gEasQumDR9121zwyV1/Chukvvg5xiNNYxwM1pn4TDvLjSfnEE6T/fXYdb1NWZ2h46Ma4htOpj9/BVP9/RZrraCm8790GhcXlSotchtrCkbT8gUobgTe9Wsd10vbTBOtes/wyIA9Jq3eYt9S7Sqw4H71RfozIyBRmtmYNl2WJaxPnU5E8vLgikKO4P5vBie0+FGiBWmZ8KzDchMZNzO1RF4+Kbd2e2LrS8GOpXdllQxBgkwoNMIwZLMFRoQ8lX/mhOLwyWznJJ30xL7yKaKHzrdXz+L8CmByxtHNzeVA5uvkJU2Im+rPOcoFokUgJU4uvTAPKo=
  on:
    tags: true
