script:
- echo "skipping tests"

deploy:
  provider: npm
  email: developers@messente.com
  api_key:
    secure: GfhA9giPkL2PGuhlgy+G25u98zpL5KLuOXVAp/UFMItLtZOAVLt8a3Qyz+a11fJXMi0c4SbpCdn71ReATqfDPGOdwksgBI5hDZgw/tokYE+bS/ebumxeND9ivpVVluu6IVc7Rto8vE5zz5l8oKWOHpjzzF6Ffm6UuhyGvsc3sYw42hG45LprOWYaz5P3jdpcu+WidaKMGCa6BB1IhvrfP9lz+ZAK5iTciE40LjG3PkQB9arxoXmbVhravChQm8CXe1DudRnyJZ32iKr+4hDvBhxLzIC595HsykKBGqmh7CaaFVFpSm4ygzXUTAWFm/7LKO64qOaC6kk60iN0Hs76N2HMqBVaYPapkLoB8YWXJ3/Ml0hfguCncWa7wtHA8xYIX2IEp9k2OW+Bf66hXm9t46hk8k/q8Wx79C3r0o3fz2PCbb9pgYpXhD3NKdndHb5T82LwGM5ntRlssSr/GVdWn3fBRjJ1/BwO/3EKZAeD3Sl4f4j6HjqAu4aVGgbXxWcSKf7CUwUFre0x+dD2TeySTj/5hoUgYSqpJgLIvy4ODGuqx3ooRv3p1tsnDEC5vsJMiRGf/RyURWsDDNhF2olyBi/VAeGLp9Nrugc0t+yxl4gMn8cJffO99aFqLWNC2HDv9NA1OMJPk8IsEkO4J5NTpNLSn1Mz8jYwUsxp+UqKQu0=
  on:
    tags: true
