/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorItemOmnichannel from './ErrorItemOmnichannel';
import ErrorOmnichannel from './ErrorOmnichannel';
import MessageResult from './MessageResult';
import OmniMessageCreateSuccessResponse from './OmniMessageCreateSuccessResponse';

/**
 * The BulkOmniMessageCreateSuccessResponseMessagesInner model module.
 * @module model/BulkOmniMessageCreateSuccessResponseMessagesInner
 * @version 2.2.0
 */
class BulkOmniMessageCreateSuccessResponseMessagesInner {
    /**
     * Constructs a new <code>BulkOmniMessageCreateSuccessResponseMessagesInner</code>.
     * @alias module:model/BulkOmniMessageCreateSuccessResponseMessagesInner
     * @param {(module:model/ErrorOmnichannel|module:model/OmniMessageCreateSuccessResponse)} instance The actual instance to initialize BulkOmniMessageCreateSuccessResponseMessagesInner.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "OmniMessageCreateSuccessResponse") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                OmniMessageCreateSuccessResponse.validateJSON(instance); // throw an exception if no match
                // create OmniMessageCreateSuccessResponse from JS object
                this.actualInstance = OmniMessageCreateSuccessResponse.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into OmniMessageCreateSuccessResponse
            errorMessages.push("Failed to construct OmniMessageCreateSuccessResponse: " + err)
        }

        try {
            if (typeof instance === "ErrorOmnichannel") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                ErrorOmnichannel.validateJSON(instance); // throw an exception if no match
                // create ErrorOmnichannel from JS object
                this.actualInstance = ErrorOmnichannel.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into ErrorOmnichannel
            errorMessages.push("Failed to construct ErrorOmnichannel: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `BulkOmniMessageCreateSuccessResponseMessagesInner` with oneOf schemas ErrorOmnichannel, OmniMessageCreateSuccessResponse. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `BulkOmniMessageCreateSuccessResponseMessagesInner` with oneOf schemas ErrorOmnichannel, OmniMessageCreateSuccessResponse. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>BulkOmniMessageCreateSuccessResponseMessagesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BulkOmniMessageCreateSuccessResponseMessagesInner} obj Optional instance to populate.
     * @return {module:model/BulkOmniMessageCreateSuccessResponseMessagesInner} The populated <code>BulkOmniMessageCreateSuccessResponseMessagesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        return new BulkOmniMessageCreateSuccessResponseMessagesInner(data);
    }

    /**
     * Gets the actual instance, which can be <code>ErrorOmnichannel</code>, <code>OmniMessageCreateSuccessResponse</code>.
     * @return {(module:model/ErrorOmnichannel|module:model/OmniMessageCreateSuccessResponse)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>ErrorOmnichannel</code>, <code>OmniMessageCreateSuccessResponse</code>.
     * @param {(module:model/ErrorOmnichannel|module:model/OmniMessageCreateSuccessResponse)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = BulkOmniMessageCreateSuccessResponseMessagesInner.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of BulkOmniMessageCreateSuccessResponseMessagesInner from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/BulkOmniMessageCreateSuccessResponseMessagesInner} An instance of BulkOmniMessageCreateSuccessResponseMessagesInner.
     */
    static fromJSON = function(json_string){
        return BulkOmniMessageCreateSuccessResponseMessagesInner.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * List of messages that compose the omnimessage
 * @member {Array.<module:model/MessageResult>} messages
 */
BulkOmniMessageCreateSuccessResponseMessagesInner.prototype['messages'] = undefined;

/**
 * Phone number in e.164 format
 * @member {String} to
 */
BulkOmniMessageCreateSuccessResponseMessagesInner.prototype['to'] = undefined;

/**
 * Unique identifier for the omnimessage
 * @member {String} omnimessage_id
 */
BulkOmniMessageCreateSuccessResponseMessagesInner.prototype['omnimessage_id'] = undefined;

/**
 * An array of errors
 * @member {Array.<module:model/ErrorItemOmnichannel>} errors
 */
BulkOmniMessageCreateSuccessResponseMessagesInner.prototype['errors'] = undefined;


BulkOmniMessageCreateSuccessResponseMessagesInner.OneOf = ["ErrorOmnichannel", "OmniMessageCreateSuccessResponse"];

export default BulkOmniMessageCreateSuccessResponseMessagesInner;

