/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Channel.
* @enum {}
* @readonly
*/
export default class Channel {
    
        /**
         * value: "sms"
         * @const
         */
        "sms" = "sms";

    
        /**
         * value: "viber"
         * @const
         */
        "viber" = "viber";

    
        /**
         * value: "whatsapp"
         * @const
         */
        "whatsapp" = "whatsapp";

    
        /**
         * value: "telegram"
         * @const
         */
        "telegram" = "telegram";

    

    /**
    * Returns a <code>Channel</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Channel} The enum <code>Channel</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

