/**
 * Messente API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ContactFields'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ContactFields'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.ContactListEnvelope = factory(root.MessenteApi.ApiClient, root.MessenteApi.ContactFields);
  }
}(this, function(ApiClient, ContactFields) {
  'use strict';



  /**
   * The ContactListEnvelope model module.
   * @module model/ContactListEnvelope
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ContactListEnvelope</code>.
   * @alias module:model/ContactListEnvelope
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>ContactListEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContactListEnvelope} obj Optional instance to populate.
   * @return {module:model/ContactListEnvelope} The populated <code>ContactListEnvelope</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('contacts')) {
        obj['contacts'] = ApiClient.convertToType(data['contacts'], [ContactFields]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ContactFields>} contacts
   */
  exports.prototype['contacts'] = undefined;



  return exports;
}));


