/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContactResponseFields from './ContactResponseFields';

/**
 * The ContactListEnvelope model module.
 * @module model/ContactListEnvelope
 * @version 2.1.0
 */
class ContactListEnvelope {
    /**
     * Constructs a new <code>ContactListEnvelope</code>.
     * A container for contacts
     * @alias module:model/ContactListEnvelope
     */
    constructor() { 
        
        ContactListEnvelope.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContactListEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactListEnvelope} obj Optional instance to populate.
     * @return {module:model/ContactListEnvelope} The populated <code>ContactListEnvelope</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactListEnvelope();

            if (data.hasOwnProperty('contacts')) {
                obj['contacts'] = ApiClient.convertToType(data['contacts'], [ContactResponseFields]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContactListEnvelope</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContactListEnvelope</code>.
     */
    static validateJSON(data) {
        if (data['contacts']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['contacts'])) {
                throw new Error("Expected the field `contacts` to be an array in the JSON data but got " + data['contacts']);
            }
            // validate the optional field `contacts` (array)
            for (const item of data['contacts']) {
                ContactResponseFields.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * An array of contacts
 * @member {Array.<module:model/ContactResponseFields>} contacts
 */
ContactListEnvelope.prototype['contacts'] = undefined;






export default ContactListEnvelope;

