/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services. Use Messente API library to send and receive SMS, Viber and WhatsApp messages, blacklist phone numbers to make sure you're not sending any unwanted messages, manage contacts and groups.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 1.0.2
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContactUpdateFields model module.
 * @module model/ContactUpdateFields
 * @version 1.0.3
 */
class ContactUpdateFields {
    /**
     * Constructs a new <code>ContactUpdateFields</code>.
     * A container for fields of a contact
     * @alias module:model/ContactUpdateFields
     */
    constructor() { 
        
        ContactUpdateFields.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContactUpdateFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactUpdateFields} obj Optional instance to populate.
     * @return {module:model/ContactUpdateFields} The populated <code>ContactUpdateFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactUpdateFields();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('custom')) {
                obj['custom'] = ApiClient.convertToType(data['custom'], 'String');
            }
            if (data.hasOwnProperty('custom2')) {
                obj['custom2'] = ApiClient.convertToType(data['custom2'], 'String');
            }
            if (data.hasOwnProperty('custom3')) {
                obj['custom3'] = ApiClient.convertToType(data['custom3'], 'String');
            }
            if (data.hasOwnProperty('custom4')) {
                obj['custom4'] = ApiClient.convertToType(data['custom4'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The email of the contact
 * @member {String} email
 */
ContactUpdateFields.prototype['email'] = undefined;

/**
 * The first name of the contact
 * @member {String} firstName
 */
ContactUpdateFields.prototype['firstName'] = undefined;

/**
 * The last name of the contact
 * @member {String} lastName
 */
ContactUpdateFields.prototype['lastName'] = undefined;

/**
 * The company of the contact
 * @member {String} company
 */
ContactUpdateFields.prototype['company'] = undefined;

/**
 * The title of the contact
 * @member {String} title
 */
ContactUpdateFields.prototype['title'] = undefined;

/**
 * The first custom field
 * @member {String} custom
 */
ContactUpdateFields.prototype['custom'] = undefined;

/**
 * The second custom field
 * @member {String} custom2
 */
ContactUpdateFields.prototype['custom2'] = undefined;

/**
 * The third custom field
 * @member {String} custom3
 */
ContactUpdateFields.prototype['custom3'] = undefined;

/**
 * The fourth custom field
 * @member {String} custom4
 */
ContactUpdateFields.prototype['custom4'] = undefined;






export default ContactUpdateFields;

