/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ErrorCodeOmnichannel.
* @enum {}
* @readonly
*/
export default class ErrorCodeOmnichannel {
    
        /**
         * value: "101"
         * @const
         */
        "101" = "101";

    
        /**
         * value: "102"
         * @const
         */
        "102" = "102";

    
        /**
         * value: "103"
         * @const
         */
        "103" = "103";

    
        /**
         * value: "104"
         * @const
         */
        "104" = "104";

    
        /**
         * value: "105"
         * @const
         */
        "105" = "105";

    
        /**
         * value: "106"
         * @const
         */
        "106" = "106";

    
        /**
         * value: "107"
         * @const
         */
        "107" = "107";

    

    /**
    * Returns a <code>ErrorCodeOmnichannel</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ErrorCodeOmnichannel} The enum <code>ErrorCodeOmnichannel</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

