/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services. Use Messente API library to send and receive SMS, Viber and WhatsApp messages, blacklist phone numbers to make sure you're not sending any unwanted messages, manage contacts and groups.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 1.0.2
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorCodePhonebook from './ErrorCodePhonebook';
import ErrorTitlePhonebook from './ErrorTitlePhonebook';

/**
 * The ErrorItemPhonebook model module.
 * @module model/ErrorItemPhonebook
 * @version 1.0.3
 */
class ErrorItemPhonebook {
    /**
     * Constructs a new <code>ErrorItemPhonebook</code>.
     * A container for Phonebook API error
     * @alias module:model/ErrorItemPhonebook
     * @param title {module:model/ErrorTitlePhonebook} 
     * @param detail {String} Free form more detailed description of the error
     * @param code {module:model/ErrorCodePhonebook} 
     */
    constructor(title, detail, code) { 
        
        ErrorItemPhonebook.initialize(this, title, detail, code);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, detail, code) { 
        obj['title'] = title;
        obj['detail'] = detail;
        obj['code'] = code;
    }

    /**
     * Constructs a <code>ErrorItemPhonebook</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ErrorItemPhonebook} obj Optional instance to populate.
     * @return {module:model/ErrorItemPhonebook} The populated <code>ErrorItemPhonebook</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorItemPhonebook();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ErrorTitlePhonebook.constructFromObject(data['title']);
            }
            if (data.hasOwnProperty('detail')) {
                obj['detail'] = ApiClient.convertToType(data['detail'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ErrorCodePhonebook.constructFromObject(data['code']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ErrorTitlePhonebook} title
 */
ErrorItemPhonebook.prototype['title'] = undefined;

/**
 * Free form more detailed description of the error
 * @member {String} detail
 */
ErrorItemPhonebook.prototype['detail'] = undefined;

/**
 * @member {module:model/ErrorCodePhonebook} code
 */
ErrorItemPhonebook.prototype['code'] = undefined;






export default ErrorItemPhonebook;

