/**
 * Messente API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorItemPhonebook'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ErrorItemPhonebook'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.ErrorPhonebook = factory(root.MessenteApi.ApiClient, root.MessenteApi.ErrorItemPhonebook);
  }
}(this, function(ApiClient, ErrorItemPhonebook) {
  'use strict';



  /**
   * The ErrorPhonebook model module.
   * @module model/ErrorPhonebook
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ErrorPhonebook</code>.
   * @alias module:model/ErrorPhonebook
   * @class
   * @param errors {Array.<module:model/ErrorItemPhonebook>} 
   */
  var exports = function(errors) {
    var _this = this;

    _this['errors'] = errors;
  };

  /**
   * Constructs a <code>ErrorPhonebook</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ErrorPhonebook} obj Optional instance to populate.
   * @return {module:model/ErrorPhonebook} The populated <code>ErrorPhonebook</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('errors')) {
        obj['errors'] = ApiClient.convertToType(data['errors'], [ErrorItemPhonebook]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ErrorItemPhonebook>} errors
   */
  exports.prototype['errors'] = undefined;



  return exports;
}));


