/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services. Use Messente API library to send and receive SMS, Viber and WhatsApp messages, blacklist phone numbers to make sure you're not sending any unwanted messages, manage contacts and groups.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 1.0.2
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GroupResponseFields from './GroupResponseFields';

/**
 * The GroupListEnvelope model module.
 * @module model/GroupListEnvelope
 * @version 1.0.3
 */
class GroupListEnvelope {
    /**
     * Constructs a new <code>GroupListEnvelope</code>.
     * A container for groups
     * @alias module:model/GroupListEnvelope
     */
    constructor() { 
        
        GroupListEnvelope.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GroupListEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GroupListEnvelope} obj Optional instance to populate.
     * @return {module:model/GroupListEnvelope} The populated <code>GroupListEnvelope</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupListEnvelope();

            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], [GroupResponseFields]);
            }
        }
        return obj;
    }


}

/**
 * An array of groups
 * @member {Array.<module:model/GroupResponseFields>} groups
 */
GroupListEnvelope.prototype['groups'] = undefined;






export default GroupListEnvelope;

