/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services. Use Messente API library to send and receive SMS, Viber and WhatsApp messages, blacklist phone numbers to make sure you're not sending any unwanted messages, manage contacts and groups.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 1.0.2
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessageResult from './MessageResult';

/**
 * The OmniMessageCreateSuccessResponse model module.
 * @module model/OmniMessageCreateSuccessResponse
 * @version 1.0.3
 */
class OmniMessageCreateSuccessResponse {
    /**
     * Constructs a new <code>OmniMessageCreateSuccessResponse</code>.
     * A container for a response received after successfully created omnimessage
     * @alias module:model/OmniMessageCreateSuccessResponse
     * @param messages {Array.<module:model/MessageResult>} List of messages that compose the omnimessage
     * @param to {String} Phone number in e.164 format
     * @param omnimessageId {String} Unique identifier for the omnimessage
     */
    constructor(messages, to, omnimessageId) { 
        
        OmniMessageCreateSuccessResponse.initialize(this, messages, to, omnimessageId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, messages, to, omnimessageId) { 
        obj['messages'] = messages;
        obj['to'] = to;
        obj['omnimessage_id'] = omnimessageId;
    }

    /**
     * Constructs a <code>OmniMessageCreateSuccessResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OmniMessageCreateSuccessResponse} obj Optional instance to populate.
     * @return {module:model/OmniMessageCreateSuccessResponse} The populated <code>OmniMessageCreateSuccessResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OmniMessageCreateSuccessResponse();

            if (data.hasOwnProperty('messages')) {
                obj['messages'] = ApiClient.convertToType(data['messages'], [MessageResult]);
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('omnimessage_id')) {
                obj['omnimessage_id'] = ApiClient.convertToType(data['omnimessage_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * List of messages that compose the omnimessage
 * @member {Array.<module:model/MessageResult>} messages
 */
OmniMessageCreateSuccessResponse.prototype['messages'] = undefined;

/**
 * Phone number in e.164 format
 * @member {String} to
 */
OmniMessageCreateSuccessResponse.prototype['to'] = undefined;

/**
 * Unique identifier for the omnimessage
 * @member {String} omnimessage_id
 */
OmniMessageCreateSuccessResponse.prototype['omnimessage_id'] = undefined;






export default OmniMessageCreateSuccessResponse;

