/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PriceNetworks'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PriceNetworks'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.Price = factory(root.MessenteApi.ApiClient, root.MessenteApi.PriceNetworks);
  }
}(this, function(ApiClient, PriceNetworks) {
  'use strict';



  /**
   * The Price model module.
   * @module model/Price
   * @version 2.4.2
   */

  /**
   * Constructs a new <code>Price</code>.
   * An object containing the pricing information for a given country
   * @alias module:model/Price
   * @class
   * @param country {String} The alpha-2 code for the country
   * @param name {String} The name of the country
   * @param prefix {String} The country code prefix
   * @param networks {Array.<module:model/PriceNetworks>} A list of networks available in the country
   */
  var exports = function(country, name, prefix, networks) {
    var _this = this;

    _this['country'] = country;
    _this['name'] = name;
    _this['prefix'] = prefix;
    _this['networks'] = networks;
  };

  /**
   * Constructs a <code>Price</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Price} obj Optional instance to populate.
   * @return {module:model/Price} The populated <code>Price</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('prefix')) {
        obj['prefix'] = ApiClient.convertToType(data['prefix'], 'String');
      }
      if (data.hasOwnProperty('networks')) {
        obj['networks'] = ApiClient.convertToType(data['networks'], [PriceNetworks]);
      }
    }
    return obj;
  }

  /**
   * The alpha-2 code for the country
   * @member {String} country
   */
  exports.prototype['country'] = undefined;
  /**
   * The name of the country
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The country code prefix
   * @member {String} prefix
   */
  exports.prototype['prefix'] = undefined;
  /**
   * A list of networks available in the country
   * @member {Array.<module:model/PriceNetworks>} networks
   */
  exports.prototype['networks'] = undefined;



  return exports;
}));


