/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RcsMedia', 'model/RcsSuggestion'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RcsMedia'), require('./RcsSuggestion'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.RcsCardContent = factory(root.MessenteApi.ApiClient, root.MessenteApi.RcsMedia, root.MessenteApi.RcsSuggestion);
  }
}(this, function(ApiClient, RcsMedia, RcsSuggestion) {
  'use strict';



  /**
   * The RcsCardContent model module.
   * @module model/RcsCardContent
   * @version 2.5.0
   */

  /**
   * Constructs a new <code>RcsCardContent</code>.
   * RCS Card Content
   * @alias module:model/RcsCardContent
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>RcsCardContent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RcsCardContent} obj Optional instance to populate.
   * @return {module:model/RcsCardContent} The populated <code>RcsCardContent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('media')) {
        obj['media'] = RcsMedia.constructFromObject(data['media']);
      }
      if (data.hasOwnProperty('suggestions')) {
        obj['suggestions'] = ApiClient.convertToType(data['suggestions'], [RcsSuggestion]);
      }
    }
    return obj;
  }

  /**
   * Title of the card content
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * Description of the card content
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {module:model/RcsMedia} media
   */
  exports.prototype['media'] = undefined;
  /**
   * List of suggestions that the recipient can use to respond.
   * @member {Array.<module:model/RcsSuggestion>} suggestions
   */
  exports.prototype['suggestions'] = undefined;



  return exports;
}));


