/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.RcsCreateCalendarEventAction = factory(root.MessenteApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The RcsCreateCalendarEventAction model module.
   * @module model/RcsCreateCalendarEventAction
   * @version 2.5.0
   */

  /**
   * Constructs a new <code>RcsCreateCalendarEventAction</code>.
   * Action to create a calendar event.
   * @alias module:model/RcsCreateCalendarEventAction
   * @class
   * @param start_time {String} The start time of the event.
   * @param end_time {String} The end time of the event.
   * @param title {String} The title of the event.
   * @param description {String} The description of the event.
   */
  var exports = function(start_time, end_time, title, description) {
    var _this = this;

    _this['start_time'] = start_time;
    _this['end_time'] = end_time;
    _this['title'] = title;
    _this['description'] = description;
  };

  /**
   * Constructs a <code>RcsCreateCalendarEventAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RcsCreateCalendarEventAction} obj Optional instance to populate.
   * @return {module:model/RcsCreateCalendarEventAction} The populated <code>RcsCreateCalendarEventAction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('start_time')) {
        obj['start_time'] = ApiClient.convertToType(data['start_time'], 'String');
      }
      if (data.hasOwnProperty('end_time')) {
        obj['end_time'] = ApiClient.convertToType(data['end_time'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
    }
    return obj;
  }

  /**
   * The start time of the event.
   * @member {String} start_time
   */
  exports.prototype['start_time'] = undefined;
  /**
   * The end time of the event.
   * @member {String} end_time
   */
  exports.prototype['end_time'] = undefined;
  /**
   * The title of the event.
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * The description of the event.
   * @member {String} description
   */
  exports.prototype['description'] = undefined;



  return exports;
}));


