/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.RcsContentInfo = factory(root.MessenteApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The RcsContentInfo model module.
   * @module model/RcsContentInfo
   * @version 2.5.0
   */

  /**
   * Constructs a new <code>RcsContentInfo</code>.
   * RCS content info object.
   * @alias module:model/RcsContentInfo
   * @class
   * @param file_url {String} Required file URL
   * @param force_refresh {Boolean} Force refresh the content
   */
  var exports = function(file_url, force_refresh) {
    var _this = this;

    _this['file_url'] = file_url;
    _this['force_refresh'] = force_refresh;
  };

  /**
   * Constructs a <code>RcsContentInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RcsContentInfo} obj Optional instance to populate.
   * @return {module:model/RcsContentInfo} The populated <code>RcsContentInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('file_url')) {
        obj['file_url'] = ApiClient.convertToType(data['file_url'], 'String');
      }
      if (data.hasOwnProperty('thumbnail_url')) {
        obj['thumbnail_url'] = ApiClient.convertToType(data['thumbnail_url'], 'String');
      }
      if (data.hasOwnProperty('force_refresh')) {
        obj['force_refresh'] = ApiClient.convertToType(data['force_refresh'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Required file URL
   * @member {String} file_url
   */
  exports.prototype['file_url'] = undefined;
  /**
   * Optional thumbnail URL
   * @member {String} thumbnail_url
   */
  exports.prototype['thumbnail_url'] = undefined;
  /**
   * Force refresh the content
   * @member {Boolean} force_refresh
   */
  exports.prototype['force_refresh'] = undefined;



  return exports;
}));


