/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RcsSuggestedAction', 'model/RcsSuggestedReply'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RcsSuggestedAction'), require('./RcsSuggestedReply'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.RcsSuggestion = factory(root.MessenteApi.ApiClient, root.MessenteApi.RcsSuggestedAction, root.MessenteApi.RcsSuggestedReply);
  }
}(this, function(ApiClient, RcsSuggestedAction, RcsSuggestedReply) {
  'use strict';



  /**
   * The RcsSuggestion model module.
   * @module model/RcsSuggestion
   * @version 2.5.0
   */

  /**
   * Constructs a new <code>RcsSuggestion</code>.
   * Exactly one of reply or action must be provided
   * @alias module:model/RcsSuggestion
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>RcsSuggestion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RcsSuggestion} obj Optional instance to populate.
   * @return {module:model/RcsSuggestion} The populated <code>RcsSuggestion</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('reply')) {
        obj['reply'] = RcsSuggestedReply.constructFromObject(data['reply']);
      }
      if (data.hasOwnProperty('action')) {
        obj['action'] = RcsSuggestedAction.constructFromObject(data['action']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/RcsSuggestedReply} reply
   */
  exports.prototype['reply'] = undefined;
  /**
   * @member {module:model/RcsSuggestedAction} action
   */
  exports.prototype['action'] = undefined;



  return exports;
}));


