/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.1.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RcsLatLng'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RcsLatLng'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.RcsViewLocationAction = factory(root.MessenteApi.ApiClient, root.MessenteApi.RcsLatLng);
  }
}(this, function(ApiClient, RcsLatLng) {
  'use strict';



  /**
   * The RcsViewLocationAction model module.
   * @module model/RcsViewLocationAction
   * @version 2.6.0
   */

  /**
   * Constructs a new <code>RcsViewLocationAction</code>.
   * Action to view a location on a map.
   * @alias module:model/RcsViewLocationAction
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>RcsViewLocationAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RcsViewLocationAction} obj Optional instance to populate.
   * @return {module:model/RcsViewLocationAction} The populated <code>RcsViewLocationAction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('lat_long')) {
        obj['lat_long'] = RcsLatLng.constructFromObject(data['lat_long']);
      }
      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
      if (data.hasOwnProperty('query')) {
        obj['query'] = ApiClient.convertToType(data['query'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/RcsLatLng} lat_long
   */
  exports.prototype['lat_long'] = undefined;
  /**
   * The label of the pin dropped at latLong.
   * @member {String} label
   */
  exports.prototype['label'] = undefined;
  /**
   * (Optional, only supported on Android Messages clients) Instead of specifying a latLong (and optionally, a label), the agent can specify a query string. For default map apps that support search functionality (including Google Maps), tapping this suggested action results in a location search centered around the user's current location.              For instance, setting the query string to \"Growing Tree Bank\" will show all Growing Tree Bank locations in the user's vicinity. Setting the query string to \"1600 Amphitheater Parkway, Mountain View, CA 94043\" will select that specific address, regardless of the user's location.       
   * @member {String} query
   */
  exports.prototype['query'] = undefined;



  return exports;
}));


