/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.StatisticsReportSettings = factory(root.MessenteApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The StatisticsReportSettings model module.
   * @module model/StatisticsReportSettings
   * @version 1.5.0
   */

  /**
   * Constructs a new <code>StatisticsReportSettings</code>.
   * A container for statistics report settings
   * @alias module:model/StatisticsReportSettings
   * @class
   * @param startDate {Date} Start date for the report
   * @param endDate {Date} End date for the report
   */
  var exports = function(startDate, endDate) {
    var _this = this;

    _this['start_date'] = startDate;
    _this['end_date'] = endDate;
  };

  /**
   * Constructs a <code>StatisticsReportSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StatisticsReportSettings} obj Optional instance to populate.
   * @return {module:model/StatisticsReportSettings} The populated <code>StatisticsReportSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('start_date')) {
        obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
      }
      if (data.hasOwnProperty('end_date')) {
        obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
      }
      if (data.hasOwnProperty('message_types')) {
        obj['message_types'] = ApiClient.convertToType(data['message_types'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Start date for the report
   * @member {Date} start_date
   */
  exports.prototype['start_date'] = undefined;
  /**
   * End date for the report
   * @member {Date} end_date
   */
  exports.prototype['end_date'] = undefined;
  /**
   * Optional list of message types (sms, viber, whatsapp, hlr, telegram)
   * @member {Array.<String>} message_types
   */
  exports.prototype['message_types'] = undefined;



  return exports;
}));


