/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MobileNetwork from './MobileNetwork';

/**
 * The SyncNumberLookupResult model module.
 * @module model/SyncNumberLookupResult
 * @version 2.0.0
 */
class SyncNumberLookupResult {
    /**
     * Constructs a new <code>SyncNumberLookupResult</code>.
     * Info about a phone number
     * @alias module:model/SyncNumberLookupResult
     * @param number {String} Phone number in e.164 format
     */
    constructor(number) { 
        
        SyncNumberLookupResult.initialize(this, number);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, number) { 
        obj['number'] = number;
    }

    /**
     * Constructs a <code>SyncNumberLookupResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SyncNumberLookupResult} obj Optional instance to populate.
     * @return {module:model/SyncNumberLookupResult} The populated <code>SyncNumberLookupResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SyncNumberLookupResult();

            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'String');
            }
            if (data.hasOwnProperty('roaming')) {
                obj['roaming'] = ApiClient.convertToType(data['roaming'], 'Boolean');
            }
            if (data.hasOwnProperty('ported')) {
                obj['ported'] = ApiClient.convertToType(data['ported'], 'Boolean');
            }
            if (data.hasOwnProperty('roamingNetwork')) {
                obj['roamingNetwork'] = MobileNetwork.constructFromObject(data['roamingNetwork']);
            }
            if (data.hasOwnProperty('currentNetwork')) {
                obj['currentNetwork'] = MobileNetwork.constructFromObject(data['currentNetwork']);
            }
            if (data.hasOwnProperty('originalNetwork')) {
                obj['originalNetwork'] = MobileNetwork.constructFromObject(data['originalNetwork']);
            }
            if (data.hasOwnProperty('portedNetwork')) {
                obj['portedNetwork'] = MobileNetwork.constructFromObject(data['portedNetwork']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SyncNumberLookupResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SyncNumberLookupResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SyncNumberLookupResult.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['number'] && !(typeof data['number'] === 'string' || data['number'] instanceof String)) {
            throw new Error("Expected the field `number` to be a primitive type in the JSON string but got " + data['number']);
        }
        // validate the optional field `roamingNetwork`
        if (data['roamingNetwork']) { // data not null
          MobileNetwork.validateJSON(data['roamingNetwork']);
        }
        // validate the optional field `currentNetwork`
        if (data['currentNetwork']) { // data not null
          MobileNetwork.validateJSON(data['currentNetwork']);
        }
        // validate the optional field `originalNetwork`
        if (data['originalNetwork']) { // data not null
          MobileNetwork.validateJSON(data['originalNetwork']);
        }
        // validate the optional field `portedNetwork`
        if (data['portedNetwork']) { // data not null
          MobileNetwork.validateJSON(data['portedNetwork']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

SyncNumberLookupResult.RequiredProperties = ["number"];

/**
 * Phone number in e.164 format
 * @member {String} number
 */
SyncNumberLookupResult.prototype['number'] = undefined;

/**
 * Indicates if a number is roaming
 * @member {Boolean} roaming
 */
SyncNumberLookupResult.prototype['roaming'] = undefined;

/**
 * Indicates if a number is ported
 * @member {Boolean} ported
 */
SyncNumberLookupResult.prototype['ported'] = undefined;

/**
 * @member {module:model/MobileNetwork} roamingNetwork
 */
SyncNumberLookupResult.prototype['roamingNetwork'] = undefined;

/**
 * @member {module:model/MobileNetwork} currentNetwork
 */
SyncNumberLookupResult.prototype['currentNetwork'] = undefined;

/**
 * @member {module:model/MobileNetwork} originalNetwork
 */
SyncNumberLookupResult.prototype['originalNetwork'] = undefined;

/**
 * @member {module:model/MobileNetwork} portedNetwork
 */
SyncNumberLookupResult.prototype['portedNetwork'] = undefined;

/**
 * Status of the phone number
 * @member {module:model/SyncNumberLookupResult.StatusEnum} status
 */
SyncNumberLookupResult.prototype['status'] = undefined;

/**
 * Indicates if any error occurred while handling the request
 * @member {Object} error
 */
SyncNumberLookupResult.prototype['error'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
SyncNumberLookupResult['StatusEnum'] = {

    /**
     * value: "ON"
     * @const
     */
    "ON": "ON",

    /**
     * value: "OFF"
     * @const
     */
    "OFF": "OFF",

    /**
     * value: "INVALID"
     * @const
     */
    "INVALID": "INVALID",

    /**
     * value: "UNKNOWN"
     * @const
     */
    "UNKNOWN": "UNKNOWN"
};



export default SyncNumberLookupResult;

