/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Viber model module.
 * @module model/Viber
 * @version 2.1.0
 */
class Viber {
    /**
     * Constructs a new <code>Viber</code>.
     * Viber message content
     * @alias module:model/Viber
     */
    constructor() { 
        
        Viber.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Viber</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Viber} obj Optional instance to populate.
     * @return {module:model/Viber} The populated <code>Viber</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Viber();

            if (data.hasOwnProperty('sender')) {
                obj['sender'] = ApiClient.convertToType(data['sender'], 'String');
            }
            if (data.hasOwnProperty('validity')) {
                obj['validity'] = ApiClient.convertToType(data['validity'], 'Number');
            }
            if (data.hasOwnProperty('ttl')) {
                obj['ttl'] = ApiClient.convertToType(data['ttl'], 'Number');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
            if (data.hasOwnProperty('button_url')) {
                obj['button_url'] = ApiClient.convertToType(data['button_url'], 'String');
            }
            if (data.hasOwnProperty('button_text')) {
                obj['button_text'] = ApiClient.convertToType(data['button_text'], 'String');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Viber</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Viber</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['sender'] && !(typeof data['sender'] === 'string' || data['sender'] instanceof String)) {
            throw new Error("Expected the field `sender` to be a primitive type in the JSON string but got " + data['sender']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // ensure the json data is a string
        if (data['image_url'] && !(typeof data['image_url'] === 'string' || data['image_url'] instanceof String)) {
            throw new Error("Expected the field `image_url` to be a primitive type in the JSON string but got " + data['image_url']);
        }
        // ensure the json data is a string
        if (data['button_url'] && !(typeof data['button_url'] === 'string' || data['button_url'] instanceof String)) {
            throw new Error("Expected the field `button_url` to be a primitive type in the JSON string but got " + data['button_url']);
        }
        // ensure the json data is a string
        if (data['button_text'] && !(typeof data['button_text'] === 'string' || data['button_text'] instanceof String)) {
            throw new Error("Expected the field `button_text` to be a primitive type in the JSON string but got " + data['button_text']);
        }
        // ensure the json data is a string
        if (data['channel'] && !(typeof data['channel'] === 'string' || data['channel'] instanceof String)) {
            throw new Error("Expected the field `channel` to be a primitive type in the JSON string but got " + data['channel']);
        }

        return true;
    }


}



/**
 * Phone number or alphanumeric sender name
 * @member {String} sender
 */
Viber.prototype['sender'] = undefined;

/**
 * After how many minutes this channel is considered as failed and the next channel is attempted.       Only one of \"ttl\" and \"validity\" can be used.
 * @member {Number} validity
 */
Viber.prototype['validity'] = undefined;

/**
 * After how many seconds this channel is considered as failed and the next channel is attempted.       Only one of \"ttl\" and \"validity\" can be used.
 * @member {Number} ttl
 */
Viber.prototype['ttl'] = undefined;

/**
 * Plaintext content for Viber
 * @member {String} text
 */
Viber.prototype['text'] = undefined;

/**
 * URL for the embedded image    Valid combinations:    1) image_url,    2) text, image_url, button_url, button_text
 * @member {String} image_url
 */
Viber.prototype['image_url'] = undefined;

/**
 * URL of the button, must be specified along with ''text'', ''button_text'' and ''image_url'' (optional)
 * @member {String} button_url
 */
Viber.prototype['button_url'] = undefined;

/**
 * Must be specified along with ''text'', ''button_url'', ''button_text'', ''image_url'' (optional)
 * @member {String} button_text
 */
Viber.prototype['button_text'] = undefined;

/**
 * The channel used to deliver the message
 * @member {module:model/Viber.ChannelEnum} channel
 * @default 'viber'
 */
Viber.prototype['channel'] = 'viber';





/**
 * Allowed values for the <code>channel</code> property.
 * @enum {String}
 * @readonly
 */
Viber['ChannelEnum'] = {

    /**
     * value: "viber"
     * @const
     */
    "viber": "viber"
};



export default Viber;

