/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.1.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ViberCarouselItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ViberCarouselItem'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.ViberCarousel = factory(root.MessenteApi.ApiClient, root.MessenteApi.ViberCarouselItem);
  }
}(this, function(ApiClient, ViberCarouselItem) {
  'use strict';



  /**
   * The ViberCarousel model module.
   * @module model/ViberCarousel
   * @version 2.6.0
   */

  /**
   * Constructs a new <code>ViberCarousel</code>.
   * Viber carousel object.
   * @alias module:model/ViberCarousel
   * @class
   * @param items {Array.<module:model/ViberCarouselItem>} Carousel items. Must contain between 2 and 5 items.
   */
  var exports = function(items) {
    var _this = this;

    _this['items'] = items;
  };

  /**
   * Constructs a <code>ViberCarousel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ViberCarousel} obj Optional instance to populate.
   * @return {module:model/ViberCarousel} The populated <code>ViberCarousel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [ViberCarouselItem]);
      }
    }
    return obj;
  }

  /**
   * Carousel items. Must contain between 2 and 5 items.
   * @member {Array.<module:model/ViberCarouselItem>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


