/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.ViberVideo = factory(root.MessenteApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ViberVideo model module.
   * @module model/ViberVideo
   * @version 2.2.0
   */

  /**
   * Constructs a new <code>ViberVideo</code>.
   * Viber video object
   * @alias module:model/ViberVideo
   * @class
   * @param url {String} URL pointing to the video resource.
   * @param thumbnail {String} URL pointing to the video thumbnail resource.
   * @param file_size {Number} Size of the video file in bytes. Cannot be larger than 200MB.
   * @param duration {Number} Duration of the video in seconds. Cannot be longer than 600 seconds.
   */
  var exports = function(url, thumbnail, file_size, duration) {
    var _this = this;

    _this['url'] = url;
    _this['thumbnail'] = thumbnail;
    _this['file_size'] = file_size;
    _this['duration'] = duration;
  };

  /**
   * Constructs a <code>ViberVideo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ViberVideo} obj Optional instance to populate.
   * @return {module:model/ViberVideo} The populated <code>ViberVideo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('thumbnail')) {
        obj['thumbnail'] = ApiClient.convertToType(data['thumbnail'], 'String');
      }
      if (data.hasOwnProperty('file_size')) {
        obj['file_size'] = ApiClient.convertToType(data['file_size'], 'Number');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
      }
    }
    return obj;
  }

  /**
   * URL pointing to the video resource.
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * URL pointing to the video thumbnail resource.
   * @member {String} thumbnail
   */
  exports.prototype['thumbnail'] = undefined;
  /**
   * Size of the video file in bytes. Cannot be larger than 200MB.
   * @member {Number} file_size
   */
  exports.prototype['file_size'] = undefined;
  /**
   * Duration of the video in seconds. Cannot be longer than 600 seconds.
   * @member {Number} duration
   */
  exports.prototype['duration'] = undefined;



  return exports;
}));


