/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.1.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.ViberCarouselButton = factory(root.MessenteApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ViberCarouselButton model module.
   * @module model/ViberCarouselButton
   * @version 2.6.0
   */

  /**
   * Constructs a new <code>ViberCarouselButton</code>.
   * Viber carousel button object.
   * @alias module:model/ViberCarouselButton
   * @class
   * @param label {String} Button label text.
   * @param action_url {String} URL opened when the button is clicked.
   */
  var exports = function(label, action_url) {
    var _this = this;

    _this['label'] = label;
    _this['action_url'] = action_url;
  };

  /**
   * Constructs a <code>ViberCarouselButton</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ViberCarouselButton} obj Optional instance to populate.
   * @return {module:model/ViberCarouselButton} The populated <code>ViberCarouselButton</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
      if (data.hasOwnProperty('action_url')) {
        obj['action_url'] = ApiClient.convertToType(data['action_url'], 'String');
      }
    }
    return obj;
  }

  /**
   * Button label text.
   * @member {String} label
   */
  exports.prototype['label'] = undefined;
  /**
   * URL opened when the button is clicked.
   * @member {String} action_url
   */
  exports.prototype['action_url'] = undefined;



  return exports;
}));


