/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.1.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ViberCarouselButton'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ViberCarouselButton'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.ViberCarouselItem = factory(root.MessenteApi.ApiClient, root.MessenteApi.ViberCarouselButton);
  }
}(this, function(ApiClient, ViberCarouselButton) {
  'use strict';



  /**
   * The ViberCarouselItem model module.
   * @module model/ViberCarouselItem
   * @version 2.6.0
   */

  /**
   * Constructs a new <code>ViberCarouselItem</code>.
   * Viber carousel item object.
   * @alias module:model/ViberCarouselItem
   * @class
   * @param title {String} Carousel item title.
   * @param image_url {String} URL of the carousel item image.
   * @param primary_button {module:model/ViberCarouselButton} 
   */
  var exports = function(title, image_url, primary_button) {
    var _this = this;

    _this['title'] = title;
    _this['image_url'] = image_url;
    _this['primary_button'] = primary_button;
  };

  /**
   * Constructs a <code>ViberCarouselItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ViberCarouselItem} obj Optional instance to populate.
   * @return {module:model/ViberCarouselItem} The populated <code>ViberCarouselItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('image_url')) {
        obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
      }
      if (data.hasOwnProperty('primary_button')) {
        obj['primary_button'] = ViberCarouselButton.constructFromObject(data['primary_button']);
      }
      if (data.hasOwnProperty('secondary_button')) {
        obj['secondary_button'] = ViberCarouselButton.constructFromObject(data['secondary_button']);
      }
    }
    return obj;
  }

  /**
   * Carousel item title.
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * URL of the carousel item image.
   * @member {String} image_url
   */
  exports.prototype['image_url'] = undefined;
  /**
   * @member {module:model/ViberCarouselButton} primary_button
   */
  exports.prototype['primary_button'] = undefined;
  /**
   * @member {module:model/ViberCarouselButton} secondary_button
   */
  exports.prototype['secondary_button'] = undefined;



  return exports;
}));


