/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.WhatsAppCurrency = factory(root.MessenteApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The WhatsAppCurrency model module.
   * @module model/WhatsAppCurrency
   * @version 2.1.0
   */

  /**
   * Constructs a new <code>WhatsAppCurrency</code>.
   * Whatsapp currency object.
   * @alias module:model/WhatsAppCurrency
   * @class
   * @param fallbackValue {String} Default text if localization fails.
   * @param code {String} Currency code as defined in ISO 4217.
   * @param amount1000 {String} Amount multiplied by 1000.
   */
  var exports = function(fallbackValue, code, amount1000) {
    var _this = this;

    _this['fallback_value'] = fallbackValue;
    _this['code'] = code;
    _this['amount_1000'] = amount1000;
  };

  /**
   * Constructs a <code>WhatsAppCurrency</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WhatsAppCurrency} obj Optional instance to populate.
   * @return {module:model/WhatsAppCurrency} The populated <code>WhatsAppCurrency</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('fallback_value')) {
        obj['fallback_value'] = ApiClient.convertToType(data['fallback_value'], 'String');
      }
      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
      if (data.hasOwnProperty('amount_1000')) {
        obj['amount_1000'] = ApiClient.convertToType(data['amount_1000'], 'String');
      }
    }
    return obj;
  }

  /**
   * Default text if localization fails.
   * @member {String} fallback_value
   */
  exports.prototype['fallback_value'] = undefined;
  /**
   * Currency code as defined in ISO 4217.
   * @member {String} code
   */
  exports.prototype['code'] = undefined;
  /**
   * Amount multiplied by 1000.
   * @member {String} amount_1000
   */
  exports.prototype['amount_1000'] = undefined;



  return exports;
}));


