/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/WhatsappPagination', 'model/WhatsappTemplateResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WhatsappPagination'), require('./WhatsappTemplateResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.WhatsappListTemplatesResponse = factory(root.MessenteApi.ApiClient, root.MessenteApi.WhatsappPagination, root.MessenteApi.WhatsappTemplateResponse);
  }
}(this, function(ApiClient, WhatsappPagination, WhatsappTemplateResponse) {
  'use strict';



  /**
   * The WhatsappListTemplatesResponse model module.
   * @module model/WhatsappListTemplatesResponse
   * @version 2.3.0
   */

  /**
   * Constructs a new <code>WhatsappListTemplatesResponse</code>.
   * Whatsapp Cloud API list of templates response
   * @alias module:model/WhatsappListTemplatesResponse
   * @class
   * @param templates {Array.<module:model/WhatsappTemplateResponse>} List of templates
   * @param paging {module:model/WhatsappPagination} 
   */
  var exports = function(templates, paging) {
    var _this = this;

    _this['templates'] = templates;
    _this['paging'] = paging;
  };

  /**
   * Constructs a <code>WhatsappListTemplatesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WhatsappListTemplatesResponse} obj Optional instance to populate.
   * @return {module:model/WhatsappListTemplatesResponse} The populated <code>WhatsappListTemplatesResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('templates')) {
        obj['templates'] = ApiClient.convertToType(data['templates'], [WhatsappTemplateResponse]);
      }
      if (data.hasOwnProperty('paging')) {
        obj['paging'] = WhatsappPagination.constructFromObject(data['paging']);
      }
    }
    return obj;
  }

  /**
   * List of templates
   * @member {Array.<module:model/WhatsappTemplateResponse>} templates
   */
  exports.prototype['templates'] = undefined;
  /**
   * @member {module:model/WhatsappPagination} paging
   */
  exports.prototype['paging'] = undefined;



  return exports;
}));


