/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.WhatsAppImage = factory(root.MessenteApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The WhatsAppImage model module.
   * @module model/WhatsAppImage
   * @version 2.4.1
   */

  /**
   * Constructs a new <code>WhatsAppImage</code>.
   * WhatsApp image content. Either \&quot;id\&quot; or \&quot;link\&quot; must be provided, but not both.
   * @alias module:model/WhatsAppImage
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>WhatsAppImage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WhatsAppImage} obj Optional instance to populate.
   * @return {module:model/WhatsAppImage} The populated <code>WhatsAppImage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('caption')) {
        obj['caption'] = ApiClient.convertToType(data['caption'], 'String');
      }
      if (data.hasOwnProperty('mime_type')) {
        obj['mime_type'] = ApiClient.convertToType(data['mime_type'], 'String');
      }
      if (data.hasOwnProperty('link')) {
        obj['link'] = ApiClient.convertToType(data['link'], 'String');
      }
    }
    return obj;
  }

  /**
   * Unique identifier for the image file.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Caption for the image.
   * @member {String} caption
   */
  exports.prototype['caption'] = undefined;
  /**
   * MIME type of the image file.
   * @member {String} mime_type
   */
  exports.prototype['mime_type'] = undefined;
  /**
   * URL link to the image file.
   * @member {String} link
   */
  exports.prototype['link'] = undefined;



  return exports;
}));


