/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WhatsAppComponent from './WhatsAppComponent';
import WhatsAppLanguage from './WhatsAppLanguage';

/**
 * The WhatsAppTemplate model module.
 * @module model/WhatsAppTemplate
 * @version 2.2.0
 */
class WhatsAppTemplate {
    /**
     * Constructs a new <code>WhatsAppTemplate</code>.
     * Whatsapp Cloud API template
     * @alias module:model/WhatsAppTemplate
     * @param name {String} Name of the template
     * @param language {module:model/WhatsAppLanguage} 
     */
    constructor(name, language) { 
        
        WhatsAppTemplate.initialize(this, name, language);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, language) { 
        obj['name'] = name;
        obj['language'] = language;
    }

    /**
     * Constructs a <code>WhatsAppTemplate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WhatsAppTemplate} obj Optional instance to populate.
     * @return {module:model/WhatsAppTemplate} The populated <code>WhatsAppTemplate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WhatsAppTemplate();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = WhatsAppLanguage.constructFromObject(data['language']);
            }
            if (data.hasOwnProperty('components')) {
                obj['components'] = ApiClient.convertToType(data['components'], [WhatsAppComponent]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WhatsAppTemplate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WhatsAppTemplate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WhatsAppTemplate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `language`
        if (data['language']) { // data not null
          WhatsAppLanguage.validateJSON(data['language']);
        }
        if (data['components']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['components'])) {
                throw new Error("Expected the field `components` to be an array in the JSON data but got " + data['components']);
            }
            // validate the optional field `components` (array)
            for (const item of data['components']) {
                WhatsAppComponent.validateJSON(item);
            };
        }

        return true;
    }


}

WhatsAppTemplate.RequiredProperties = ["name", "language"];

/**
 * Name of the template
 * @member {String} name
 */
WhatsAppTemplate.prototype['name'] = undefined;

/**
 * @member {module:model/WhatsAppLanguage} language
 */
WhatsAppTemplate.prototype['language'] = undefined;

/**
 * List of template components
 * @member {Array.<module:model/WhatsAppComponent>} components
 */
WhatsAppTemplate.prototype['components'] = undefined;






export default WhatsAppTemplate;

