/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services. Use Messente API library to send and receive SMS, Viber and WhatsApp messages, blacklist phone numbers to make sure you're not sending any unwanted messages, manage contacts and groups.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 1.0.2
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WhatsAppText model module.
 * @module model/WhatsAppText
 * @version 1.0.3
 */
class WhatsAppText {
    /**
     * Constructs a new <code>WhatsAppText</code>.
     * A text
     * @alias module:model/WhatsAppText
     * @param body {String} Plaintext content for WhatsApp, can contain URLs, emojis and formatting
     */
    constructor(body) { 
        
        WhatsAppText.initialize(this, body);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, body) { 
        obj['body'] = body;
    }

    /**
     * Constructs a <code>WhatsAppText</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WhatsAppText} obj Optional instance to populate.
     * @return {module:model/WhatsAppText} The populated <code>WhatsAppText</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WhatsAppText();

            if (data.hasOwnProperty('preview_url')) {
                obj['preview_url'] = ApiClient.convertToType(data['preview_url'], 'Boolean');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Whether to display link preview if the message contains a hyperlink
 * @member {Boolean} preview_url
 * @default true
 */
WhatsAppText.prototype['preview_url'] = true;

/**
 * Plaintext content for WhatsApp, can contain URLs, emojis and formatting
 * @member {String} body
 */
WhatsAppText.prototype['body'] = undefined;






export default WhatsAppText;

