/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.WhatsAppMedia = factory(root.MessenteApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The WhatsAppMedia model module.
   * @module model/WhatsAppMedia
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>WhatsAppMedia</code>.
   * Whatsapp media object.
   * @alias module:model/WhatsAppMedia
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>WhatsAppMedia</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WhatsAppMedia} obj Optional instance to populate.
   * @return {module:model/WhatsAppMedia} The populated <code>WhatsAppMedia</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('link')) {
        obj['link'] = ApiClient.convertToType(data['link'], 'String');
      }
      if (data.hasOwnProperty('caption')) {
        obj['caption'] = ApiClient.convertToType(data['caption'], 'String');
      }
      if (data.hasOwnProperty('filename')) {
        obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
      }
    }
    return obj;
  }

  /**
   * The media object ID. Do not use this field when message type is set to text.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The protocol and URL of the media to be sent. Use only with HTTP/HTTPS URLs.       Do not use this field when message type is set to text.
   * @member {String} link
   */
  exports.prototype['link'] = undefined;
  /**
   * Media asset caption. Do not use with audio or sticker media.
   * @member {String} caption
   */
  exports.prototype['caption'] = undefined;
  /**
   * Describes the filename for the specific document. Use only with document media.
   * @member {String} filename
   */
  exports.prototype['filename'] = undefined;



  return exports;
}));


