/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/WhatsappTemplateCategory', 'model/WhatsappTemplateStatus'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WhatsappTemplateCategory'), require('./WhatsappTemplateStatus'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.WhatsappCreateTemplateResponse = factory(root.MessenteApi.ApiClient, root.MessenteApi.WhatsappTemplateCategory, root.MessenteApi.WhatsappTemplateStatus);
  }
}(this, function(ApiClient, WhatsappTemplateCategory, WhatsappTemplateStatus) {
  'use strict';



  /**
   * The WhatsappCreateTemplateResponse model module.
   * @module model/WhatsappCreateTemplateResponse
   * @version 2.4.1
   */

  /**
   * Constructs a new <code>WhatsappCreateTemplateResponse</code>.
   * Response for creating a WhatsApp template
   * @alias module:model/WhatsappCreateTemplateResponse
   * @class
   * @param id {String} Template ID
   * @param status {module:model/WhatsappTemplateStatus} 
   * @param category {module:model/WhatsappTemplateCategory} 
   */
  var exports = function(id, status, category) {
    var _this = this;

    _this['id'] = id;
    _this['status'] = status;
    _this['category'] = category;
  };

  /**
   * Constructs a <code>WhatsappCreateTemplateResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WhatsappCreateTemplateResponse} obj Optional instance to populate.
   * @return {module:model/WhatsappCreateTemplateResponse} The populated <code>WhatsappCreateTemplateResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = WhatsappTemplateStatus.constructFromObject(data['status']);
      }
      if (data.hasOwnProperty('category')) {
        obj['category'] = WhatsappTemplateCategory.constructFromObject(data['category']);
      }
    }
    return obj;
  }

  /**
   * Template ID
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/WhatsappTemplateStatus} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {module:model/WhatsappTemplateCategory} category
   */
  exports.prototype['category'] = undefined;



  return exports;
}));


