/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/WhatsAppComponent', 'model/WhatsAppLanguage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WhatsAppComponent'), require('./WhatsAppLanguage'));
  } else {
    // Browser globals (root is window)
    if (!root.MessenteApi) {
      root.MessenteApi = {};
    }
    root.MessenteApi.WhatsAppTemplate = factory(root.MessenteApi.ApiClient, root.MessenteApi.WhatsAppComponent, root.MessenteApi.WhatsAppLanguage);
  }
}(this, function(ApiClient, WhatsAppComponent, WhatsAppLanguage) {
  'use strict';



  /**
   * The WhatsAppTemplate model module.
   * @module model/WhatsAppTemplate
   * @version 2.2.0
   */

  /**
   * Constructs a new <code>WhatsAppTemplate</code>.
   * Whatsapp Cloud API template
   * @alias module:model/WhatsAppTemplate
   * @class
   * @param name {String} Name of the template
   * @param language {module:model/WhatsAppLanguage} 
   */
  var exports = function(name, language) {
    var _this = this;

    _this['name'] = name;
    _this['language'] = language;
  };

  /**
   * Constructs a <code>WhatsAppTemplate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WhatsAppTemplate} obj Optional instance to populate.
   * @return {module:model/WhatsAppTemplate} The populated <code>WhatsAppTemplate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('language')) {
        obj['language'] = WhatsAppLanguage.constructFromObject(data['language']);
      }
      if (data.hasOwnProperty('components')) {
        obj['components'] = ApiClient.convertToType(data['components'], [WhatsAppComponent]);
      }
    }
    return obj;
  }

  /**
   * Name of the template
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/WhatsAppLanguage} language
   */
  exports.prototype['language'] = undefined;
  /**
   * List of template components
   * @member {Array.<module:model/WhatsAppComponent>} components
   */
  exports.prototype['components'] = undefined;



  return exports;
}));


