/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BulkOmniMessageCreateSuccessResponse from '../model/BulkOmniMessageCreateSuccessResponse';
import BulkOmnimessage from '../model/BulkOmnimessage';
import ErrorOmnichannel from '../model/ErrorOmnichannel';

/**
* BulkMessaging service.
* @module api/BulkMessagingApi
* @version 2.2.0
*/
export default class BulkMessagingApi {

    /**
    * Constructs a new BulkMessagingApi. 
    * @alias module:api/BulkMessagingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the sendBulkOmnimessage operation.
     * @callback module:api/BulkMessagingApi~sendBulkOmnimessageCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BulkOmniMessageCreateSuccessResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Sends a bulk Omnimessage
     * @param {module:model/BulkOmnimessage} bulk_omnimessage Bulk Omnimessage to be sent
     * @param {module:api/BulkMessagingApi~sendBulkOmnimessageCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BulkOmniMessageCreateSuccessResponse}
     */
    sendBulkOmnimessage(bulk_omnimessage, callback) {
      let postBody = bulk_omnimessage;
      // verify the required parameter 'bulk_omnimessage' is set
      if (bulk_omnimessage === undefined || bulk_omnimessage === null) {
        throw new Error("Missing the required parameter 'bulk_omnimessage' when calling sendBulkOmnimessage");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = BulkOmniMessageCreateSuccessResponse;
      return this.apiClient.callApi(
        '/omnimessages', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
