/**
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorStatistics from '../model/ErrorStatistics';
import StatisticsReportSettings from '../model/StatisticsReportSettings';
import StatisticsReportSuccess from '../model/StatisticsReportSuccess';

/**
* Statistics service.
* @module api/StatisticsApi
* @version 2.0.0
*/
export default class StatisticsApi {

    /**
    * Constructs a new StatisticsApi. 
    * @alias module:api/StatisticsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createStatisticsReport operation.
     * @callback module:api/StatisticsApi~createStatisticsReportCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatisticsReportSuccess} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Requests statistics reports for each country
     * @param {module:model/StatisticsReportSettings} statisticsReportSettings Settings for statistics report
     * @param {module:api/StatisticsApi~createStatisticsReportCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatisticsReportSuccess}
     */
    createStatisticsReport(statisticsReportSettings, callback) {
      let postBody = statisticsReportSettings;
      // verify the required parameter 'statisticsReportSettings' is set
      if (statisticsReportSettings === undefined || statisticsReportSettings === null) {
        throw new Error("Missing the required parameter 'statisticsReportSettings' when calling createStatisticsReport");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = StatisticsReportSuccess;
      return this.apiClient.callApi(
        '/statistics/reports', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
